[build]
  publish = "public"

[functions]
  node_bundler = "esbuild"

[build.environment]
  HUGO_VERSION = "0.71.1"

[context.deploy-preview]
  command = "npm install && npm run deploy"
  environment = { BUTTONDOWN_API_KEY = "disabled-on-branch-deploy" }

[context.branch-deploy]
  command = "npm install && npm run deploy:branch"
  environment = { BUTTONDOWN_API_KEY = "disabled-on-branch-deploy" }

[[headers]]
  for = "/index.json"
  [headers.values]
  Access-Control-Allow-Origin = "*"